#!/usr/bin/env bash
# Create tags for python by introspecting python include directories.
# python-language-server seems to work better, but I'll keep this as a backup.

# Rumor has it python tags are generated better by universal ctags.
# https://github.com/universal-ctags/ctags

libpaths=$(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))")
ctags -R --fields=+l --languages=python --python-kinds=-iv --extras=+f -f ./tags . $libpaths

